[project]
name = "api-response-kit"
version = "0.1.1"
description = "Shared schemas and utils for OLX Alert Bot"
requires-python = ">=3.10"
dependencies = [
    "pydantic",
    "httpx",
    "colorlog",
    "asyncio"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"